# Generated by Django 5.0.1 on 2024-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=13)),
                ('voip_usage', models.IntegerField()),
                ('sms_usage', models.IntegerField()),
                ('storage_usage', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=255)),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=7)),
            ],
            options={
                'unique_together': {('customer_id', 'month')},
            },
        ),
    ]
