# Generated by Django 5.0.1 on 2024-01-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='storage_usage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription',
            field=models.CharField(max_length=10),
        ),
    ]
