# Generated by Django 5.0.1 on 2024-01-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_customer_total_cost_alter_customer_storage_usage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='month',
        ),
    ]
